# Generated by Django 5.1.6 on 2025-02-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(upload_to='site/logo/')),
                ('favicon', models.ImageField(upload_to='site/favicon/')),
                ('hero_video', models.FileField(blank=True, upload_to='site/hero/')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('about_image', models.ImageField(upload_to='site/about/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('google_map_embed', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('footer_text', models.TextField()),
                ('copyright_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
