# Generated by Django 5.1.6 on 2025-02-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_about_content_sitesettings_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone2',
            field=models.CharField(blank=True, help_text='Secondary phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='preloader',
            field=models.ImageField(blank=True, help_text='Upload preloader image', upload_to='site/preloader/'),
        ),
    ]
